# Site settings
title: 刘恩斯博客
url: "https://lxyzai.github.com/liuence"    # the protocol and hostname of your site, eg. `http://zhaoyuxiang.cn/blog`
baseurl: "/liuence" # the prefix of your site uri, eg. `/bohu-jekyll-theme` or just one slash `/`
#timezone: Asia/Shanghai
description: 天道总司的个人博客网站,前端HTML、HTML5、CSS、CSS3、JavaScript、JQuery等编程经验总结分享。
# Your information
email: me@zhaoyuxiang.cn
author: Liuence
place: 浙江-杭州
domain: 互联网-电子商务
company: 杭州墨匠信息科技有限公司
position: 产品经理
school: 三峡大学
major: 核工程与核技术
resume: "http://lxyzai.com/cv"
profile: 但行好事，莫问前程
twitter_username: liuence
weibo_username:  liuence
github_username:  liuence

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: zhaoyuxiang   
# get one: https://disqus.com/admin/signup/
# duoshuo_shortname: clark-zhao  
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 2
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
